#
# SPDX-FileCopyrightText: 2022 Mercedes-Benz AG
#

# ------------------------------------------------------------------------------
# Collectd 
# - collects system information periodically and provides mechanisms to store and monitor the values in a variety of ways.
# cpu:
#   warning at 3% for avg
#   warning at 20% for now
#
# source: https://wiki.swf.daimler.com/display/APRICOT/Gen20x+Resource+Budgets
# ------------------------------------------------------------------------------

LoadPlugin "threshold"
<Plugin "threshold">
  <Plugin "processes2">
    Instance "user-collectd"
    <Type "ps_cpu_percent"> 
      WarningMax   4
      FailureMax   6
      Instance "avg"
    </Type>
    <Type "ps_cpu_percent"> 
      WarningMax   20
      FailureMax   30
      Instance "now"
    </Type>
  </Plugin>
</Plugin>
