#
# SPDX-FileCopyrightText: 2022 Mercedes-Benz AG
#

# ------------------------------------------------------------------------------
# limit used by integration test
#
# source: https://wiki.swf.daimler.com/display/APRICOT/Gen20x+Resource+Budgets
# ------------------------------------------------------------------------------

LoadPlugin "threshold"
<Plugin "threshold">
  <Plugin "processes2">
    Instance "budget-test-resmgr"
    <Type "ps_rss">
      WarningMin    5000000
      WarningMax   15000000
      FailureMin    2500000
      FailureMax   20000000
    </Type>
  </Plugin>
</Plugin>
