#
# SPDX-FileCopyrightText: 2020 Daimler AG
#

################################################################################
# global
################################################################################

Interval 1
TypesDB "./src/types.db"
TypesDB "./mbient/mbient-types.db"
ReadThreads 2
WriteThreads 1

################################################################################
# logging
################################################################################

LoadPlugin "logfile"
<Plugin "logfile">
  LogLevel "info"
  File "/tmp/collectd.log"
  Timestamp true
</Plugin>

# ------------------------------------------------------------------------------
LoadPlugin "syslog"
<Plugin "syslog">
  LogLevel notify
  NotifyLevel OKAY
</Plugin>

################################################################################
# read
################################################################################

# ------------------------------------------------------------------------------
LoadPlugin "cpu"
<Plugin "cpu">
    ReportByCpu true
    ReportByState true
    ValuesPercentage true
    ReportNumCpu true
    ReportGuestState false
    SubtractGuestState true
</Plugin>

# ------------------------------------------------------------------------------
LoadPlugin "processes2"
<Plugin "processes2">
  #ProcessMatch "name" "cmd line regex" ["user name regex" ["cgroup regex"]]
  <ProcessGroup "dev">
    CollectFileDescriptor true
    CollectContextSwitch true
    CollectMemoryMaps true
    CollectDelayAccounting true
    CollectProportionalSetSize true
    CollectCpuPercent absolute

    ProcessMatch "frank" ".*" "frank"
  </ProcessGroup>
</Plugin>


################################################################################
# write
################################################################################

# ------------------------------------------------------------------------------
LoadPlugin "unixsock"
<Plugin unixsock>
  SocketFile "/tmp/collectd.sock"
  SocketGroup "mbition"
  SocketPerms "0770"
  DeleteSocket true
</Plugin>

# ------------------------------------------------------------------------------
LoadPlugin "csv"
<Plugin "csv">
  DataDir "/tmp/collectd"
  StoreRates false
</Plugin>

