#
# SPDX-FileCopyrightText: 2020 Daimler AG
#

################################################################################
# global
################################################################################

Interval 1
TypesDB "/usr/share/collectd/types.db"
TypesDB "/usr/share/collectd/types.db.mbient"
ReadThreads 2
WriteThreads 1

################################################################################
# logging
################################################################################

LoadPlugin "logfile"
<Plugin "logfile">
  LogLevel "info"
  File "/tmp/collectd.log"
  Timestamp true
</Plugin>

################################################################################
# read
################################################################################

LoadPlugin "cpu"
<Plugin "cpu">
    ReportByCpu true
    ReportByState true
    ValuesPercentage true
    ReportNumCpu true
    ReportGuestState false
    SubtractGuestState true
</Plugin>

LoadPlugin "processes2"
<Plugin "processes2">
  #ProcessMatch "name" "cmd line regex" ["user name regex" ["cgroup regex"]]
  <ProcessGroup "dev">
    CollectFileDescriptor true
    CollectContextSwitch true
    CollectMemoryMaps true
    CollectDelayAccounting true
    CollectProportionalSetSize true
    CollectCpuPercent absolute

    ProcessMatch "UDCApplication" ".*" "udc"
  </ProcessGroup>
</Plugin>

################################################################################
# write
################################################################################

LoadPlugin "csv"
<Plugin "csv">
#  DataDir "/tmp/collectd"
  DataDir "/mnt/trace/collectd"
  StoreRates false
</Plugin>

