#
# SPDX-FileCopyrightText: 2020 Daimler AG
#

################################################################################
# global
################################################################################

Interval 1
#TypesDB "@typedb-file@"
FQDNLookup false

################################################################################
# logging
################################################################################

LoadPlugin "logfile"
<Plugin "logfile">
  LogLevel "debug"
  File "/tmp/collectd.log"
  Timestamp true
</Plugin>

LoadPlugin "syslog"
<Plugin syslog>
    LogLevel notice
</Plugin>

################################################################################
# read
################################################################################


# ------------------------------------------------------------------------------
LoadPlugin "cpu"
<Plugin "cpu">
    ReportByCpu true
    ReportByState true
    ValuesPercentage false
    ReportNumCpu false
    ReportGuestState false
    SubtractGuestState true
</Plugin>


# ------------------------------------------------------------------------------
LoadPlugin "aggregation"
<Plugin "aggregation">
  <Aggregation>
    Plugin "cpu"
    Type "cpu"
    
    GroupBy "Host"
    GroupBy "TypeInstance"
    
    CalculateSum true
    CalculateAverage true
  </Aggregation>
</Plugin>


################################################################################
# write
################################################################################

# ------------------------------------------------------------------------------
LoadPlugin "unixsock"
<Plugin unixsock>
  SocketFile "/tmp/collectd.sock"
  SocketGroup "mbition"
  SocketPerms "0770"
  DeleteSocket true
</Plugin>


# ------------------------------------------------------------------------------
LoadPlugin "write_dlt"
<Plugin "write_dlt">
    Format Graphite
    #Format JSON
    <DLT>
        AppID CLTD
        #MatchLevel "^cpu" "info"
        #MatchContext "^cpu" "CPU1"
    </DLT>
</Plugin>

# ------------------------------------------------------------------------------
LoadPlugin "csv"
<Plugin "csv">
  DataDir "/tmp/collectd"
  StoreRates false
</Plugin>

################################################################################
# filter
################################################################################

LoadPlugin "match_regex"
LoadPlugin "match_value"
LoadPlugin "match_empty_counter"

# ------------------------------------------------------------------------------
<Chain "DLT">
  <Rule "ignore_zero">
    <Match "value">
      Max 0.0
      Invert false
      Satisfy "All"
    </Match>
    Target "return"
  </Rule>
  <Rule "ignore_empty_counter">
    Match "empty_counter"
    Target "return"
  </Rule>
  <Target "write">
    Chain "write_dlt"
  </Target>
</Chain>

# ------------------------------------------------------------------------------
<Chain "CSV">
  <Rule "cpu_0">
    <Match "regex">
      Plugin "^cpu"
      PluginInstance "^[1-9]"
    </Match>
    Target "return"
  </Rule>
  <Rule "user_system">
    <Match "regex">
      TypeInstance "(idle|interrupt|nice|softirq|steal|wait)$"
    </Match>
    Target "return"
  </Rule>
  <Target "write">
    Chain "write_csv"
  </Target>
</Chain>

# ------------------------------------------------------------------------------
<Chain "PostCache">
  <Rule "DLT">
    <Target "jump">
      Chain "DLT"
    </Target>
  </Rule>
  <Rule "CSV">
    <Target "jump">
      Chain "CSV"
    </Target>
  </Rule>

  Target "stop"
</Chain>


