#
# SPDX-FileCopyrightText: 2022 Daimler AG
#

BaseDir "/tmp"
PluginDir "/mnt/usr/lib64/collectd"
TypesDB "/mnt/usr/share/collectd/types.db"
TypesDB "/mnt/usr/share/collectd/mbient-types.db"
TypesDB "/mnt/usr/share/collectd/qnx-types.db"
ReadThreads 2
WriteThreads 1
FQDNLookup false
LoadPlugin "match_regex"
Hostname SafeOS

LoadPlugin "write_dlt"
<Plugin "write_dlt">
  Format GraphiteShort
  <DLT>
    AppID CLTD
  </DLT>
  LogLevel "warning"
</Plugin>

LoadPlugin "network"
<Plugin "network">
  Server "10.210.220.1"
</Plugin>

LoadPlugin "thermal"
<LoadPlugin "cpu">
  Interval 5
</LoadPlugin>

<LoadPlugin "gpu">
  Interval 5
</LoadPlugin>

<LoadPlugin "npu">
  Interval 5
</LoadPlugin>

<LoadPlugin "netstat_qnx">
  Interval 60
</LoadPlugin>

LoadPlugin "processes"
<Plugin "processes">
  NotifyCpuPerThread false
  NotifyInSingleLine true
</Plugin>

LoadPlugin "memory"
<Plugin "memory">
    MonitorCarvout "mm_dma"
    MonitorCarvout "dma_ecc_above_4g"
    MonitorCarvout "mpic_rgb_buf"
    PerProcessCarveoutUsage "true"
</Plugin>

<Chain "PostCache">
  <Rule "ignore_processes">
    <Match "regex">
      Plugin "^processes$"
    </Match>
    <Target "stop">
    </Target>
  </Rule>
  <Target "write">
    Plugin "network"
  </Target>
</Chain>
